eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: FlightService
          uri: http://localhost:9098
          predicates:
            - Path=/flights/**
        - id: Airline
          uri: http://localhost:9097
          predicates:
            - Path=/airline/**
        - id: Passenger
          uri: http://localhost:9099
          predicates:
            - Path=/passengerinfo/**
management:
  tracing:
    sampling:
      probability: 1.0